/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as ReturnRouteImport } from './routes/return'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as CalculateurRouteImport } from './routes/calculateur'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as MonDossierRouteImport } from './routes/mon-dossier'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'

const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculateurRoute = CalculateurRouteImport.update({
  id: '/calculateur',
  path: '/calculateur',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const MonDossierRoute = MonDossierRouteImport.update({
  id: '/mon-dossier',
  path: '/mon-dossier',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnRoute = ReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/calculateur': typeof CalculateurRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRoute
  '/join': typeof JoinRoute
  '/legal': typeof LegalRoute
  '/mon-dossier': typeof MonDossierRoute
  '/network': typeof NetworkRoute
  '/return': typeof ReturnRoute
  '/stories': typeof StoriesRoute
  '/team': typeof TeamRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/': typeof InsightsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/calculateur': typeof CalculateurRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRoute
  '/join': typeof JoinRoute
  '/legal': typeof LegalRoute
  '/mon-dossier': typeof MonDossierRoute
  '/network': typeof NetworkRoute
  '/return': typeof ReturnRoute
  '/stories': typeof StoriesRoute
  '/team': typeof TeamRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights': typeof InsightsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/calculateur': typeof CalculateurRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRoute
  '/join': typeof JoinRoute
  '/legal': typeof LegalRoute
  '/mon-dossier': typeof MonDossierRoute
  '/network': typeof NetworkRoute
  '/return': typeof ReturnRoute
  '/stories': typeof StoriesRoute
  '/team': typeof TeamRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/': typeof InsightsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/calculateur'
    | '/companies'
    | '/contact'
    | '/evenements'
    | '/join'
    | '/legal'
    | '/mon-dossier'
    | '/network'
    | '/return'
    | '/stories'
    | '/team'
    | '/insights/$slug'
    | '/insights/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/calculateur'
    | '/companies'
    | '/contact'
    | '/evenements'
    | '/join'
    | '/legal'
    | '/mon-dossier'
    | '/network'
    | '/return'
    | '/stories'
    | '/team'
    | '/insights/$slug'
    | '/insights'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/admin'
    | '/calculateur'
    | '/companies'
    | '/contact'
    | '/evenements'
    | '/join'
    | '/legal'
    | '/mon-dossier'
    | '/network'
    | '/return'
    | '/stories'
    | '/team'
    | '/insights/$slug'
    | '/insights/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AdminRoute: typeof AdminRoute
  CalculateurRoute: typeof CalculateurRoute
  CompaniesRoute: typeof CompaniesRoute
  ContactRoute: typeof ContactRoute
  EvenementsRoute: typeof EvenementsRoute
  JoinRoute: typeof JoinRoute
  LegalRoute: typeof LegalRoute
  MonDossierRoute: typeof MonDossierRoute
  NetworkRoute: typeof NetworkRoute
  ReturnRoute: typeof ReturnRoute
  StoriesRoute: typeof StoriesRoute
  TeamRoute: typeof TeamRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return': {
      id: '/return'
      path: '/return'
      fullPath: '/return'
      preLoaderRoute: typeof ReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculateur': {
      id: '/calculateur'
      path: '/calculateur'
      fullPath: '/calculateur'
      preLoaderRoute: typeof CalculateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-dossier': {
      id: '/mon-dossier'
      path: '/mon-dossier'
      fullPath: '/mon-dossier'
      preLoaderRoute: typeof MonDossierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AdminRoute: AdminRoute,
  CalculateurRoute: CalculateurRoute,
  CompaniesRoute: CompaniesRoute,
  ContactRoute: ContactRoute,
  EvenementsRoute: EvenementsRoute,
  JoinRoute: JoinRoute,
  LegalRoute: LegalRoute,
  MonDossierRoute: MonDossierRoute,
  NetworkRoute: NetworkRoute,
  ReturnRoute: ReturnRoute,
  StoriesRoute: StoriesRoute,
  TeamRoute: TeamRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
