/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as ReturnRouteImport } from './routes/return'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as JoinRouteImport } from './routes/join'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnRoute = ReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRouteWithChildren
  '/join': typeof JoinRoute
  '/network': typeof NetworkRoute
  '/return': typeof ReturnRoute
  '/stories': typeof StoriesRoute
  '/insights/$slug': typeof InsightsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRouteWithChildren
  '/join': typeof JoinRoute
  '/network': typeof NetworkRoute
  '/return': typeof ReturnRoute
  '/stories': typeof StoriesRoute
  '/insights/$slug': typeof InsightsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRouteWithChildren
  '/join': typeof JoinRoute
  '/network': typeof NetworkRoute
  '/return': typeof ReturnRoute
  '/stories': typeof StoriesRoute
  '/insights/$slug': typeof InsightsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies'
    | '/contact'
    | '/insights'
    | '/join'
    | '/network'
    | '/return'
    | '/stories'
    | '/insights/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies'
    | '/contact'
    | '/insights'
    | '/join'
    | '/network'
    | '/return'
    | '/stories'
    | '/insights/$slug'
  id:
    | '__root__'
    | '/'
    | '/companies'
    | '/contact'
    | '/insights'
    | '/join'
    | '/network'
    | '/return'
    | '/stories'
    | '/insights/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesRoute: typeof CompaniesRoute
  ContactRoute: typeof ContactRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  JoinRoute: typeof JoinRoute
  NetworkRoute: typeof NetworkRoute
  ReturnRoute: typeof ReturnRoute
  StoriesRoute: typeof StoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return': {
      id: '/return'
      path: '/return'
      fullPath: '/return'
      preLoaderRoute: typeof ReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
  }
}

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesRoute: CompaniesRoute,
  ContactRoute: ContactRoute,
  InsightsRoute: InsightsRouteWithChildren,
  JoinRoute: JoinRoute,
  NetworkRoute: NetworkRoute,
  ReturnRoute: ReturnRoute,
  StoriesRoute: StoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
